name: unzip
on:
  push:
    paths: ['darbi_main_upload.zip']
  workflow_dispatch:
permissions:
  contents: write
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          unzip -oq darbi_main_upload.zip
          rm darbi_main_upload.zip
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          git commit -m "deploy new structure" || true
          git push
